### ISSUE TITLE
Consider re-licensing?

### ISSUE THREAD

**Issue by sparkiegeek** [jamesbeedy/interface-memcache#2]
Currently this interface is licensed under the GPL. Since it's fairly small, and by its nature likely to be combined with other layers and interfaces, would you consider re-licensing under AGPL (matches [layer-redis](https://github.com/jamesbeedy/layer-redis/) and [layer-lxd-proxy](https://github.com/jamesbeedy/layer-lxd-proxy/) ), or Apache (matching [charm-helpers](https://github.com/juju/charm-helpers/))?

**Comment by jamesbeedy** [comment]
@sparkiegeek +1 good call

fixed with ee6b897b84d04449c2eb0846a58a6dca313cad60
